### ISSUE TITLE
Paypal Load Dependency Failing

### ISSUE THREAD

**Issue by rmo-pking** [workarea-commerce/workarea-paypal#10]
We have implemented the latest version of this plugin(3.0.0) and we're receiving some weird behavior when accessing the site, it looks like there might be a PayPal load dependency that is failing. Since this is failing the load times for our site have become extremely long, I don't have the stack trace for the issue, but I will update this once it's received, thanks

**Comment by bencrouse** [comment]
This is fixed in v3.0.5.
